import './globals.css'
import Footer from 'src/app/components/Footer'
import Navbar from 'src/app/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar /> 
        {children}
        <Footer />
      
      </body>
    </html>
  )
}
